infobloxopen/db-controller

cmd/config/config.yaml
controllers/databaseclaim_controller.go
helm/db-controller/values.yaml

Specified the `defaultShape` as `db.t4g.medium`, which is the smallest size supported by aurora-postgresql.
Specified the `defaultEngine` as `postgres`.
RDSInstance CR is created with `Engine` based on the value provided in the DatabaseClaim CR.

Added code to allow support for 'aurora-postgresql' and RDSInstances default to graviton processors

---

pkg/dbclient/client.go
pkg/dbclient/client_test.go

key/value connection string did not require url.escape.
But did ended up reverting my prev changes and adding to the  previous escape some of the special characters with "\\". 
did add a couple of unit test to validate the changes.

fix special characters in password for key/value connection string

---

controllers/databaseclaim_controller.go
pkg/pgctl/pgctl.go
pkg/pgctl/stateEnum.go

source dsn which was pulled from the secret used by the app was lost during migration process when the app secret was updated to point to new db.
stored the dsn in a temp secret before updating the app secret (to be used for later steps by dbc)
temp secret is cleaned up at the end of the migration process

fix source admin dsn being lost during migration

---

config/postgres-exporter/deployment.yaml
controllers/databaseclaim_controller.go
pkg/postgres-exporter/render.go
pkg/postgres-exporter/render_test.go

Some apps don't have the dsn filename specified as `dsn.txt`. To support creating an exporter for these apps, this PR removes the hardcoded `dsn.txt` and supplies the dsn filename from the dbclaim.

Add dsn filename as specified in the dbclaim

---

cmd/manager/main.go
helm/db-controller/templates/deployment.yaml

`setupLog.Info` needs an even number of arguments after the initial string, which function as key-value pairs. Adding `"dbproxysidecarconfig"` back as the key, which was previously configured before it was removed.
The helm chart changes are to enable dbproxy in the controller as well as adding the webhook service port to the deployment.

Enable db proxy

---

README.md
controllers/databaseclaim_controller.go

This PR contains the following fixes:
* Exclude symbol characters from password that could cause encoding/usage issues
* Force a user/password refresh if the host changes in the DBClaim

Fix problem characters in password and force host change refresh

---

config/dbproxy/dbproxysidecar.json
dbproxy/dbproxy.go
dbproxy/pgbouncer/pgbouncer.go
webhook/webhook.go

pgbouncer seem to be escaping the password, so passing unescaped password to dbproxy to avoid double escaping.

use unescaped password for dbproxy

---

helm/db-controller/minikube.yaml

fix for https://infoblox.atlassian.net/browse/ATLAS-17514

by default disable dbproxy injection while using local/minikube testing

---

dsnexec/pkg/dsnexec/dsnexec.go
dsnexec/pkg/dsnexec/dsnexec_test.go

The existing test didn't ensure that the updated DSN was being updated. This change verifies that the UpdateDSN call updates the local state before executing the command.

update sources on change

---

cmd/config/config.yaml
controllers/databaseclaim_controller.go
helm/db-controller/values.yaml

V1 Story: [B-98504](https://www10.v1host.com/InfobloxNewV1/story.mvc/Summary?oidToken=Story%3A889790&RoomContext=TeamRoom%3A699936&concept=TeamRoom)
Added BackupRetentionPolicy flag to configure it for prod and non-prod envs

added BackupRetentionPeriod config

---

dbproxy/dbproxy.go

issue - https://infoblox.atlassian.net/browse/ATLAS-16938
when a watch is added on a file, which is volume mounted through secrets, fsnotify emits 1 or more events including REMOVE.
This is due to the underlying behaviour of updation of files upon updation of corresponding secret keys of kubernetes.
the REMOVE event emitted by fsnotify , internally removes a watch on the path/file.
We were additionally removing the watcher, which resulted into "removal of non-existent watcher"
Avoided FATAL, when fsnotify errors "removal of non-existent watcher"
Also sometimes there are more than one event emitted on secret/file change such as REMOVE and CHMOD etc. Upon which pgbouncer could have reloaded similar configuration a few times. Avoided this by caching latest db creds and verify the newer ones …

fixing fsnotify behaviour upon change in files which are volume mounted through secrets (New)

---

.github/workflows/build-main.yml
Makefile
cmd/manager/main.go
config/dsnexec/dsnexecsidecar.json
helm/db-controller/templates/certs.yaml
helm/db-controller/templates/deployment.yaml
helm/db-controller/templates/webhook.yaml
helm/db-controller/values.yaml
webhook/webhook-dsnexec.go

This is to add dsnexec as a side-car container. 
Whenever db-controller would see following two annotations, it would add the sidecar.
1. infoblox.com/remote-db-dsn-secret: < some-secret-name >
2. infoblox.com/dsnexec-config-secret: < some-secret-name >
**_remote-db-dsn-secret_** - In case of RDS, it would be the secret created by DBClaim. This would be mounted as a volume inside the sidecar. the dsn.txt file can be watched for changes (by configuring such through dsnexec config.yaml).
**_dsnexec-config-secret_** - This would be a secret which needs to be created by the apps. This should contain data as
> key: config.yaml
> value:  < config needed for dsnexec >
This would be mounted as a volume inside the sidecar. The path to config.yaml file is given to the dsnexec entrypoint.

adding dsnexec as a sidecar [new]

---

helm/db-controller/templates/webhook.yaml
webhook/webhook-dsnexec.go

There were problems injecting sidecar container. 
made two fixes - 
1. added necessary parameters  to logger as it does only take arguments in key-val pair. Without such, it fatals
2. changed service name of dsnexec  webhook to same as dbproxy. Because, there was no such service present  earlier

fixing injection issue

---

cmd/manager/main.go
controllers/databaseclaim_controller.go
controllers/dbroleclaim_controller.go
helm/db-controller/templates/deployment.yaml
helm/db-controller/values.yaml

adding V level to debug logs so they only appear in debug mode.
Added as per controller-runtime's logging documentation [here](https://github.com/kubernetes-sigs/controller-runtime/blob/main/TMP-LOGGING.md)

adding v levels to debug logs

---

pkg/pgctl/pgctl.go
pkg/pgctl/pgctl_test.go
pkg/pgctl/test/pgctl_source_test_data.sql
pkg/pgctl/test/pgctl_target_test_data.sql
pkg/pgctl/utils.go

No changes to application logic.

modified unit test to reflect RDS scenario

---

controllers/databaseclaim_controller.go
controllers/databaseclaim_controller_test.go
pkg/hostparams/hostparams.go
pkg/hostparams/hostparams_test.go

support only added to aurora
support for postgres is a TODO
ended up reverting  maxstorage setup as it requires more work and testing

Support auora io

---

pkg/pgctl/pgctl.go
pkg/pgctl/test/pgctl_source_test_data.sql

while validating migration status, the unlogged tables are ignored as these tables are not replicated

ATLAS-18563 Validate DB-Controller handles the 'unlogged' tables

---

controllers/databaseclaim_controller.go
controllers/dbc_end2end_test.go
helm/db-controller/values.yaml
pkg/hostparams/hostparams.go
pkg/hostparams/hostparams_test.go
pkg/pgctl/pgctl.go

https://infoblox.atlassian.net/browse/ATLAS-19239 - propagate crossplane error messages to dbclaim
https://infoblox.atlassian.net/browse/ATLAS-19238 - user friendly message when dbversion is not supported
https://infoblox.atlassian.net/browse/ATLAS-19233 - migration failing after 15.3 due to pg_partman issue
https://infoblox.atlassian.net/browse/ATLAS-19201 - migration failing after 15.3 due to pg_cron issue
https://infoblox.atlassian.net/browse/ATLAS-19192 - make dbversion mandatory
https://infoblox.atlassian.net/browse/ATLAS-19193 - set default db at DC

mandate dbVersion

---

Makefile
api/v1/databaseclaim_types.go
controllers/databaseclaim_controller.go
controllers/databaseclaim_controller_integ_test.go
controllers/databaseclaim_controller_test.go
controllers/dbc_end2end_test.go
controllers/dbroleclaim_controller.go
controllers/dbroleclaim_controller_test.go
controllers/suite_test.go
pkg/hostparams/hostparams.go

it appears constants were leveraged to avoid type checks in Go.
This resulted in the wrong types on several key API objects which
will be hard to fix now.
Address some bad uses of types where possible. int was used in place
of time.Duration() * time.Minute, causing confusing code.

fix many types misuses

---

Jenkinsfile
Makefile
Makefile.infoblox
cmd/config/config.yaml
cmd/main.go
internal/controller/databaseclaim_controller.go
internal/controller/databaseclaim_controller_test.go
internal/controller/dbroleclaim_controller_test.go
internal/controller/suite_test.go
internal/controller/utils.go
pkg/databaseclaim/databaseclaim.go
pkg/dbclient/client.go
test/e2e/databaseclaim_controller_integ_test.go
test/e2e/e2e_suite_test.go

PTEUDO-1096 perform reconcile tests on PR builds

PTEUDO-1096 perform reconcile tests on PR builds

---

Makefile
pkg/pgctl/pgctl_test.go
pkg/pgctl/startdb_test.go
pkg/pgctl/utils.go

- remove all sleeps that were making tests appear to work
- simple retry for migration status to poll for completion
- dont wait for postgres containers to terminate. SIGKILL and move on
- check if network is already up, create it if not found
DEMO
Before https://jenkins-cd.inca.infoblox.com/job/infobloxopen/job/db-controller/job/main/285/console
```
ok  	github.com/infobloxopen/db-controller/pkg/pgctl	80.559s	coverage: 68.4% of statements
```
After
```
ok  	github.com/infobloxopen/db-controller/pkg/pgctl	9.925s	coverage: 69.5% of statements
```

remove usage of dockertest and its awfulness

---

Makefile.infoblox
README.md
api/v1/databaseclaim_types.go
config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml
helm/db-controller/minikube.yaml
internal/controller/databaseclaim_controller_test.go
internal/controller/suite_test.go
internal/controller/utils.go
pkg/databaseclaim/claimstatus.go
pkg/databaseclaim/databaseclaim.go
pkg/dbclient/client.go
pkg/dbclient/testdb.go
pkg/hostparams/hostparams.go
pkg/hostparams/hostparams_test.go
pkg/roleclaim/roleclaim.go
test/e2e/databaseclaim_controller_integ_test.go
test/e2e/dbc_end2end_test.go
test/e2e/e2e_suite_test.go

- unit test updated to NOT use fragmentKey
- more unit tests to cover validation errors
- manageError: fetch fresh claim when writing out error
- make all status fields including connection info optional
- refresh claim method, but be careful using it
- reconcile after deleting object to finalize the finalizer
- update error status when manageclouddb fails
- check for double manageError and only log, multiple status updates are happening
- clean up the dbinstance CRs when the tests are done
- fix nil pointer error in testdb
- refresh claim before updating status

PTEUDO-1096 fix more integration tests

---

.github/workflows/build-main.yml
.github/workflows/pr.yml
.gitignore
Jenkinsfile

Jenkins has provent to be increasingly unreliable. Move critical
workflows to Github and only use Jenkins for the bare minimum
of chart signing.
Change Jenkins to only push images on commits to main
Change github actions to only push images when commits to main

use github actions for testing and pushing images

---

api/v1/databaseclaim_types.go
cmd/config/config.yaml
config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml
internal/controller/databaseclaim_controller_test.go
pkg/databaseclaim/databaseclaim.go
pkg/hostparams/hostparams.go
pkg/hostparams/hostparams_test.go
pkg/roleclaim/roleclaim.go
test/e2e/dbc_end2end_test.go

These fields were used in case a dbinstance was used. As this feature was removed, these fields are no longer valid.

Remove unused fields from claim

---

cmd/main.go
helm/db-controller/minikube.yaml
helm/db-controller/templates/mutatingwebhookconfiguration.yaml
helm/db-controller/templates/test/dbproxy.yaml
helm/db-controller/values.yaml
internal/controller/databaseclaim_controller.go
internal/webhook/dbproxy.go
pkg/basefunctions/basefunctions.go
pkg/databaseclaim/claimstatus.go
pkg/databaseclaim/databaseclaim.go
pkg/roleclaim/roleclaim.go

introduce a mandatory class based label to mutate pods
add a liveness probe to the sidecar
get rid of these compiled min and max rotation values
exit existing db reconciliation when nothing needs to happen
add status predicate event filter to databaseclaim reconciler

ensure only one db-controller attempts to mutate pod

---

helm/dashboards/files/database-controller.json

The kube state metrics chart needs to be updated before we can support databaseclaim counts.
Demo: https://grafana-csp.eu-com-1.eu.csp.infoblox.com/d/b237b85a-5ea2-4bc3-8411-504e07e0e4f3/database-controller-metrics?orgId=1&refresh=5m&from=1721242183064&to=1721245783064

update the dashboard to function. missing ksm metrics for CRs

---

helm/db-controller/templates/deployment.yaml
helm/db-controller/templates/test/dbproxy.yaml
scripts/psql-open-owners.sh

breaking change in deployment yaml. deployment has to be recreated for this to take effect
DEMO
modified to access `dwells` for demo
```
./scripts/psql-open-owners.sh identity/identity-api
Namespace: identity
DatabaseClaim: identity-api
Created: 2024-01-12T14:25:38Z
Secret: identity-api-dsn
14 identity-api
```

use unique component in deployment yaml

---

Makefile
api/v1/errors.go
helm/db-controller/minikube.yaml
helm/db-controller/minikube_gcp.yaml
pkg/databaseclaim/awsprovider.go
pkg/databaseclaim/databaseclaim.go
pkg/databaseclaim/errors.go
pkg/databaseclaim/gcpprovider.go
test/e2e/dbc_end2end_test.go
test/e2e/e2e_suite_test.go
test/utils/utils.go

Delete only things that are created by the integration test suite. Run it once at the end of the suite regardless if it fails or not. set `NOCLEANUP=1` to prevent the cleanup at the end
```
make test-e2e NODEPLOY=1
...
Ran 4 of 4 Specs in 64.201 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
```

improve test consistentcy for basic databaseclaim test

---

api/v1/databaseclaim_types.go
config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml

DEMO
```
db-controller ❯ k get dbc -n usergroups usergroups-dbapi -o wide
NAME               TYPE       VERSION   STATE   AGE    MIGRATIONSTATE
usergroups-dbapi   postgres   15.5      ready   316d   completed
db-controller ❯ k get dbc -n usergroups usergroups-dbapi
NAME               TYPE       VERSION   STATE
usergroups-dbapi   postgres   15.5      ready
```

add active db version to printer column

---

api/v1/databaseclaim_types.go
pkg/databaseclaim/databaseclaim.go
pkg/databaseclaim/secrets.go
pkg/databaseclaim/secrets_test.go
pkg/roleclaim/mockclient.go
pkg/roleclaim/roleclaim_test.go

Add 2 new keys into the main secret to store the replica DSN and URI_DSN

DEVOPS-28123 include aurora rds read replica connection information in db claim secret

---

helm/db-controller/templates/xrd.yaml

Authz depends on db-controller-crds (at a minimum). Since XRD requires crossplane CRDs to be installed (which is complex), moving this back to db-controller chart.
Fixes this issue
```
db-controller-crds   328d   False   Helm upgrade failed: failed to apply CRD no CompositeResourceDefinition with the name "xnetworkrecords.persistance.infoblox.com" found
```
Related: https://github.com/Infoblox-CTO/deployment-configurations/pull/63292

put xrd in the templates folder and turn off pruning

---

cmd/main.go

db-controller is creating objects in a shared account. It
must name these objects with a unique identifier which is
the env of the cluster. Within a cluster, all objects are
already unique.

DEVOPS-28607 refuse to start if env is not passed in

---

helm/db-controller/templates/xr.yaml
helm/db-controller/templates/xrd.yaml
helm/db-controller/values.yaml

xrds are being installed on aws clusters where they do nothing.

only install xrds/xrs on gcp clusters

---

helm/db-controller/templates/_helpers.tpl
helm/db-controller/templates/deployment.yaml
helm/db-controller/templates/tests/dbproxy.yaml

Seeing the following error deploying the current chart
```
message: |-
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 14: mapping key "app.kubernetes.io/component" already defined at line 11
```

Fix duplicate component labels

---

dbproxy/pgbouncer/config.go
dbproxy/scripts/start-pgbouncer.sh

The dbproxy is used on the same host as the client. As SSL would
be more secure, we already using SSL to secure the outbound
connection to cloud or actual database. Since this sidecar call
is local to the host, we will allow non-SSL connections. This will
ensure better usability for users of dbproxy.

PTEUDO-2041 Support SSL and non-SSL client connections

---

api/v1/dbroleclaim_types.go
config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml

```text
The DbRoleClaim CR expects the status.username  field to be set. 
However, some older version of the db-controller does not handle setting the status.username. 
To address this, we should make the DbRoleClaimStatus.username field optional.
```

PTEUDO-2095: DB role claim username should be optional

---

pkg/databaseclaim/databaseclaim.go
pkg/hostparams/hostparams.go

- [PTEUDO-1989](https://infoblox.atlassian.net/browse/PTEUDO-1989);
- The issue was that the dbversion value was being retrieved from the previously set activedb source, even when `useExistingSource` was false. This caused the dbversion to keep having the activedb dbversion, and the migration was not triggered. This PR fixes it by checking whether `useExistingSource` is true or false.

PTEUDO-1989 - Fix migration trigger check.

---

internal/controller/databaseclaim_controller_test.go
internal/controller/databasecontroller_migrate_test.go
internal/dockerdb/mockdb.go
internal/dockerdb/testdb.go
pkg/databaseclaim/databaseclaim.go
pkg/databaseclaim/secrets.go
pkg/databaseclaim/secrets_test.go

Previously, customizing the dsnname would throw a validation error
and prevent any processing of the databaseclaim. This allows the
customization but ensures the normalized fields are always
populated.
https://infoblox.atlassian.net/browse/PTEUDO-2142

PTEUDO-2142 remove validation of DSNName

---

pkg/hostparams/hostparams_test.go

We store the dbversion for looking up crossplane CRs in the
status field of the databaseclaim. This test verifies that
the databaseclaim is able to find the version when its not
the default one that the controller would use.
Enforces a unit test to ensure we lookup the activedb.dbversion. If this lookup is missing, 99% of our databases would fail to be resolved as seen in [PTOCP-1756](https://infoblox.atlassian.net/browse/PTOCP-1756)
ref: https://github.com/infobloxopen/db-controller/pull/369

PTOCP-1756 check activedb.dbversion is respected

---

internal/controller/dbroleclaim_controller_test.go

Added the following new DbRoleClaim Tests , creating a roleclaim in new namespace for a Dbclaim existing in another namespace
Output of running test
```
STEP: Opening a connection to the database using the DSN from the secret in the new namespace 
Connection to the database successful
STEP: Running the query to get the tables in the new namespace 
Table: users, Owner: postgres, Size: 16 kB, Description:   
< Exit [It] should successfully reconcile the resource 
……..
[AfterSuite] PASSED [1.126 seconds]
------------------------------
Ran 2 of 11 Specs in 5.742 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
ok      github.com/infobloxopen/db-controller/internal/controller       6.667s
```

PTEUDO-1602: DBRoleClaim Tests Update

---

dbproxy/scripts/start-pgbouncer.sh

DEMO
ran the test and watched pods stay ready/live for 15 password cycles
```
~ ❯ k -n dwells describe po dwells-dbproxy-test | tail -n15
Events:
Type     Reason                           Age                 From      Message
----     ------                           ----                ----      -------
Normal   Scheduled                        46m                 trimaran  Successfully assigned dwells/dwells-dbproxy-test to ip-172-60-1-11.ec2.internal
Normal   Pulled                           46m                 kubelet   Container image "harbor.services.sdp.infoblox.com/proxy_cache_docker_hub/postgres:15" already present on machine
Normal   Created                          46m                 kubelet   Created container init
Normal   Started                          46m …
```

update start-pgbouncer to exit after 60seconds

---

cmd/main.go
helm/db-controller/templates/deployment.yaml
helm/db-controller/values.yaml
internal/webhook/dbproxy.go
internal/webhook/dbproxy_test.go
internal/webhook/defaulter.go
internal/webhook/dsnexec.go
internal/webhook/dsnexec_test.go
internal/webhook/suite_test.go

Make the probes optional as a fallback that the liveness probe
failure issues are not resolved.

DEVOPS-30046 optional sidecar probes

---

internal/controller/databaseclaim_controller_test.go
pkg/databaseclaim/databaseclaim.go
pkg/dbuser/dbuser.go

- This PR fixes the user/password rotation logic that was broken;
- It fixes it by checking if the current user is empty and activeDB status struct has a URI, if yes, this means there is an activeDB already with an active user and not an initial database creation;
- Refer to: https://infoblox.atlassian.net/browse/PTEUDO-2215?focusedCommentId=4007818

DEVOPS-30870: fix password rotation logic

---

helm/db-controller/templates/tests/dbproxy.yaml
helm/db-controller/templates/tests/dsnexec.yaml
helm/db-controller/templates/tests/roleclaim.yaml
internal/webhook/dbproxy.go
internal/webhook/dsnexec.go
internal/webhook/dsnexec_test.go

dsnexec does not use the standard mount volumes of dbproxy. So
it can't use probes pointing to those mount volumes. Removed
the liveness probe and setup the readiness probe to point
to DBPROXY_CREDENTIAL env variable.
https://infoblox.atlassian.net/browse/DEVOPS-30642

DEVOPS-30642 disable liveness probes

---

helm/db-controller/templates/tests/dbproxy.yaml
helm/db-controller/templates/tests/dsnexec.yaml
helm/db-controller/templates/tests/roleclaim.yaml
internal/controller/databaseclaim_controller_test.go
internal/webhook/dbproxy.go
internal/webhook/dsnexec.go
internal/webhook/dsnexec_test.go
pkg/databaseclaim/claimstatus.go

Merge release branch into main

Merge release liveness

---

pkg/dbclient/client.go

This is to fix the missing CREATE permission on the public schema on GCP databases;
```
identity-api=> SELECT has_schema_privilege('identity-api', 'public', 'CREATE');
has_schema_privilege
----------------------
f
(1 row)
identity-api=> SELECT has_schema_privilege('identity-api_a', 'public', 'CREATE');
has_schema_privilege
----------------------
f
(1 row)
identity-api=> SELECT has_schema_privilege('identity-api_b', 'public', 'CREATE');
has_schema_privilege
----------------------
f
(1 row)
```

Add CREATE privilege grant for schema in database permissions

---

pkg/databaseclaim/databaseclaim.go
pkg/dbclient/client.go

Included Fixes:
Today we don't install the default extensions(Not sure if it's intentional or a bug, even though CreateDefaultExtensions method is called while reconciling new db the code actually bypass the installation part --> Fixed
In case of reconciling existing db  the method is not called itself. --> Fixed default extensions to be installed as part of existing db reconciliation.

PTEUDO-2426:relation pg_stat_statements does not exist at character 668

---

helm/db-controller/files/grafana-dashboard.json
helm/db-controller/values.yaml
internal/metrics/databaseclaim.go
pkg/dbclient/client.go
pkg/metrics/metrics.go

Modified dbcliam metrics to include additional labels.
Created grafana alerts to notify when db reconcile errors out.
Fixed grafana dashboard datasource configuration.
https://grafana-csp.box-3.eng.test.infoblox.com/d/b237b85a-5ea2-4bc3-8411-504e07e0e4f3/database-controller-metrics?orgId=1&refresh=5m

PTEUDO-2457:Create alerts when dbclaim reconcile throws error.
