infobloxopen/db-controller

controllers/databaseclaim_controller.go, go.mod, go.sum, helm/db-controller/minikube.yaml, helm/db-controller/templates/secrets.yaml, helm/dbclaim-sample/templates/dbclaim-sample.yaml
Added added DB, users support
Added support to read master password from secrets
Some refactoring
=> Adding support to create database, create, update db users

Jenkinsfile, Makefile, api/v1/databaseclaim_types.go, build.properties.in, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, controllers/databaseclaim_controller.go, helm/db-controller-crds/crds/persistance.atlas.infoblox.com_databaseclaims.yaml, helm/dbclaim-sample/templates/dbclaim-sample.yaml
changed CRD field names to camel case
updated CI to push helm charts
updated Makefile targets
=> Changing crd field names

controllers/databaseclaim_controller.go
added  owner reference to connection info secret
improved error handling
=> adding owner reference to connection info secret

controllers/databaseclaim_controller.go, controllers/databaseclaim_controller_test.go, pkg/dbclient/dbClient.go
Added controller UTs
Moved DB logic to separate package
=> Unit tests

Makefile, cmd/manager/main.go, go.mod, helm/db-controller/templates/deployment.yaml, helm/db-controller/values.yaml, pkg/dbclient/dbClient.go, pkg/metrics/controllerMetrics.go
added service metrics
updated deployment annotations
=> Add support for telemetry to db-controller

Makefile, controllers/databaseclaim_controller.go, helm/db-controller/minikube.yaml, helm/db-controller/templates/deployment.yaml, helm/db-controller/templates/secrets.yaml, helm/db-controller/templates/spaces.yaml, helm/db-controller/values.yaml
added space support to deployment
fixed incorrect image tag
=> Add space support to deployment

api/v1/databaseclaim_types.go, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, controllers/databaseclaim_controller.go, helm/db-controller-crds/crds/persistance.atlas.infoblox.com_databaseclaims.yaml, helm/dbclaim-sample/templates/dbclaim-sample.yaml, pkg/dbclient/dbClient.go, pkg/dbclient/dbClient_test.go
connection info secret contains DSN
=> updating connection info secret

cmd/manager/main.go, helm/dashboards/files/database-controller.json, helm/db-controller/templates/deployment.yaml, helm/db-controller/templates/pdb.yaml, helm/db-controller/values.yaml, pkg/config/config.go
updated db-controller dashboard
added health and readiness probes
=> Update db-controller dashboard

build/Dockerfile, controllers/databaseclaim_controller.go, helm/dashboards/files/database-controller.json, pkg/config/config.go
updated dashboard metrics
addressed deepsource comments
=> Update dashboard metrics

Dockerfile, Makefile, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml
Changes to pull in Makefile changes for Jenkins, we will eventually move everything to Github Actions
=> Changes to pull in Makefile changes from older release

.gitignore, controllers/databaseclaim_controller.go
https://pkg.go.dev/github.com/go-logr/logr@v1.2.0#Logger.Error
=> use key/value pair when in args to log.Error

controllers/databaseclaim_controller.go, pkg/dbclient/dbClient.go, pkg/dbclient/dbClient_test.go, pkg/dbclient/interface.go
Reworked client interface to be more extensible and remove stutter in calls ie. dbclient.DBClientFactory. Renamed interfaces to use er for go standards
=> tweak some bugs in the clienter interface

controllers/databaseclaim_controller.go
There is a time delay in secret getting updated fully. initially only password is set..and it takes about 5 minutes for endpoint to be updated.
=> requeue if secret is not complete

cmd/config/config.yaml, controllers/databaseclaim_controller.go, helm/db-controller/values.yaml
Provides the functionality to enable the multiAZ setting for Postgres and Aurora-Postgres instances.
=> Added Support for multiAZ database deployments

Dockerfile, controllers/databaseclaim_controller.go, helm/db-controller/minikube.yaml, helm/db-controller/values.yaml, pkg/pgctl/pgctl.go, pkg/pgctl/pgctl_test.go, pkg/pgctl/stateEnum.go, pkg/pgctl/test/pgctl_test.sql
- updated to support postgres version 13
- compare before and after table count to validate migration completion
- added wait time for datatransfer to complete
(wait time was only partially implemented as it introduced an issue were dbc loses access to source secret)
=> make 13 default version for postgres

controllers/conversion.go
Resolves the issue seen with duplicate tags overwriting existing tags
=> Fix duplicate tags bug

helm/db-controller/templates/cluster-role.yaml
ConfigMap is in core, not `apps`.
=> fix role for configmap

cmd/manager/main.go, config/samples/corev1_secret.yaml, controllers/dbroleclaim_controller.go, helm/db-controller/templates/cluster-role.yaml
- checks for associated dbclaim and creates the necessary secret
- fixed clusterrole issue (impacting box-3)
TBD
=> initial checkin of dbrole logic

api/v1/dbroleclaim_types.go, cmd/manager/main.go, config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml, config/rbac/role.yaml, config/samples/persistance_v1_databaseclaim.yaml, config/samples/persistance_v1_dbroleclaim.yaml, controllers/dbroleclaim_controller.go, helm/db-controller-crds/crd/persistance.atlas.infoblox.com_dbroleclaims.yaml
- checks for associated dbclaim and creates the necessary secret
Next step - work on unit tests
=> added watch for databaseclaim changes

Dockerfile, api/v1/databaseclaim_types.go, api/v1/zz_generated.deepcopy.go, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, helm/db-controller-crds/crd/persistance.atlas.infoblox.com_databaseclaims.yaml
CRD change to include the flag.
implementation of the role is work in progress
=> Flag to enable/disable replication role for a db user

api/v1/databaseclaim_types.go, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, helm/db-controller-crds/crd/persistance.atlas.infoblox.com_databaseclaims.yaml, helm/db-controller/templates/deployment.yaml
to help with get output 
added more details to -o wide
included a short name
added tpl to prefix - to make Drew happy
=> added additional print columns 

pkg/dbclient/client.go, pkg/dbclient/client_test.go
applied the grant in the application db level to take affect
=> grant db permission mandated in postgres15 at the application db level

dsnexec/pkg/dsnexec/dsnexec.go, dsnexec/pkg/dsnexec/dsnexec_test.go, dsnexec/pkg/dsnexec/nulldb/nulldb.go
acquire writelock when updating DSN
=> Lock config

controllers/databaseclaim_controller.go, helm/db-controller/values.yaml
tested on box-3
Values in `forProvider` set by db-controller config:
=> adding options to toggle perf insight and cloudwatch logs

controllers/databaseclaim_controller.go
This scenario was not originally expected - but came across this while performing sso-identity migration.
=> ATLAS-18108 Add support to dbc to change from using local vpc rds to useExistingSource rds

controllers/databaseclaim_controller.go, controllers/databaseclaim_controller_test.go, pkg/hostparams/hostparams.go, pkg/hostparams/hostparams_test.go
Reverts infobloxopen/db-controller#207
=> Revert "Support auora io"

controllers/databaseclaim_controller.go, controllers/databaseclaim_controller_test.go, pkg/hostparams/hostparams.go
Reverts infobloxopen/db-controller#198
=> Revert "feature-storage-autoscale/db-controller-changes"

pkg/postgres-exporter/render.go
https://infoblox.atlassian.net/browse/ATLAS-18508
=> [ATLAS-18508] update resource limit causing OOMKiled for dbclaim-exporter

Makefile, api/v1/databaseclaim_types.go, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, controllers/dbc_end2end_test.go, controllers/suite_test.go, helm/db-controller-crds/crd/persistance.atlas.infoblox.com_databaseclaims.yaml
logic to handle deletion policy is still TBD
wanted to update crd first to enable testing
=> update end to end tests. add support for deletion policy in crd

Dockerfile, controllers/databaseclaim_controller.go, controllers/dbc_end2end_test.go
fix for https://infoblox.atlassian.net/browse/ATLAS-18815 by caching the master secret 
fix for https://infoblox.atlassian.net/browse/ATLAS-19009 by setting the createrole permission at the base role level
=> Cachesecret

Makefile, controllers/databaseclaim_controller.go, go.mod, helm/db-controller/values.yaml, pkg/dbclient/client.go, pkg/dbclient/interface.go, pkg/pgctl/pgdump.go
fix for https://infoblox.atlassian.net/browse/ATLAS-19014
=> create partman extension in partman schema and grant access

cmd/main.go, config/crd/bases/persistance.atlas.infoblox.com_databaseclaims.yaml, config/crd/bases/persistance.atlas.infoblox.com_dbroleclaims.yaml
Load viper config when starting the application.
=> Load viper config

Makefile, Makefile.infoblox, pkg/postgres-exporter/render.go, scripts/check-context.sh, test/e2e/databaseclaim_controller_integ_test.go, test/e2e/dbc_end2end_test.go, test/e2e/e2e_suite_test.go, test/e2e/e2e_test.go
- Calling make as much as possible so testing is simpler for devs
- Basic test to prove that controller is up in the cluster
- Added conditions to make that only specific clusters will be deployed into
=> PTEUDO-1096 scaffolding of integration tests

Jenkinsfile, Makefile
Can't share lazy loaded variables to an include when used as a dependency target
=> have jenkins exercise more steps in PRs

pkg/dbclient/client.go, pkg/roleclaim/roleclaim_test.go
the command that grants access to a role was change to another version and it broke how tables are created and accessed in new databases.
=> DEVOPS-27631: Fix command that grants access to a role

dbproxy/cmd/dbproxy/main.go, dbproxy/dbproxy.go, dbproxy/pgbouncer/pgbouncer.go, helm/db-controller/minikube.yaml, helm/db-controller/templates/test/dbproxy.yaml, helm/db-controller/templates/xr.yaml, helm/db-controller/templates/xrd.yaml, helm/db-controller/values.yaml, internal/webhook/dbproxy.go
- change tests to verify readiness probe
- fix logging in dbproxy pgbouncer pkg
=> fix syntax errors in probes

Makefile, Makefile.infoblox, helm/db-controller/minikube_gcp.yaml, pkg/databaseclaim/databaseclaim.go, scripts/check-context.sh, test/e2e/dbc_end2end_test.go, test/e2e/e2e_suite_test.go, test/e2e/utils.go
check crossplane crs individually before checking dbc
add resource ready cr checks
=> support integration tests on aws and gcp

pkg/databaseclaim/awsprovider.go
- Ticket: https://infoblox.atlassian.net/browse/DEVOPS-28310;
=> DEVOPS-28310: pass maintenance window from dbclaim to crossplane db instance

internal/dockerdb/testdb.go, pkg/pgctl/pgctl.go, pkg/pgctl/pgctl_test.go
- Implemented tests to validate the migration process in the pgctl package.
=> PTEUDO-1577: added migration tests for pgctl package

pkg/databaseclaim/awsprovider.go, test/e2e/dbc_end2end_test.go
DEMO
fresh dbinstance works correctly on provider-aws
```
Ran 3 of 3 Specs in 601.588 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestE2E (601.59s)
PASS
ok      github.com/infobloxopen/db-controller/test/e2e  601.603s
```
=> Integration tests

pkg/databaseclaim/databaseclaim.go, pkg/metrics/metrics.go
- https://infoblox.atlassian.net/browse/PTEUDO-1179
=> PTEUDO-1179: metrics

cmd/main.go, helm/db-controller/minikube.yaml, helm/db-controller/templates/mutatingwebhookconfiguration.yaml, pkg/databaseclaim/databaseclaim.go, pkg/dbclient/client.go, pkg/dbclient/client_test.go
- https://infoblox.atlassian.net/browse/PTEUDO-1691;
=> PTEUDO-1691: remove database name from dbclient

cmd/main.go, internal/metrics/databaseclaim.go, pkg/databaseclaim/databaseclaim.go, pkg/metrics/metrics.go
- https://infoblox.atlassian.net/browse/PTEUDO-1658
=> PTEUDO-1658: Improving custom dbc metrics publishing

Jenkinsfile, Makefile.infoblox
This includes a debugging code for the `.id` command to debug an error happening on the latest Jenkins build: [/job/db-controller/job/main/370/console](https://jenkins-cd.inca.infoblox.com/job/infobloxopen/job/db-controller/job/main/370/console);
=> Include debugging code.

pkg/hostparams/hostparams.go
Revert a change to fix: https://infoblox.atlassian.net/browse/PTOCP-1756;
=> PTOCP-1756: revert change

internal/webhook/conversion.go, internal/webhook/conversion_test.go, internal/webhook/defaulter.go, scripts/check-sidecars.sh, scripts/psql-open.sh
A bug in the conversion webhook added dbproxy mutating labels
when only dsnexec was requested. This would cause issues if
the pod could not handle dbproxy listening on port 5432.
=> DEVOPS-30046 DEVOPS-30239 dsnexec conversion injects dbproxy

pkg/dbclient/client.go
- Ticket: [DEVOPS-31391](https://infoblox.atlassian.net/browse/DEVOPS-31391);
=> DEVOPS-31391: Fix permissions on sequences and other DB objects

pkg/databaseclaim/databaseclaim.go, pkg/postgres-exporter/render.go
Jira: https://infoblox.atlassian.net/browse/PTEUDO-2141
=> PTEUDO-2141:Update postgres exporter.

internal/controller/databaseclaim_controller.go
- [DEVOPS-32240](https://infoblox.atlassian.net/browse/DEVOPS-32240)
=> DEVOPS-32240: Enhance event filtering to include label changes in DatabaseClaim controller
